### ISSUE TITLE
Release v0.2.0 Checklist

### ISSUE THREAD

**Issue by warlicks** [warlicks/noaaoceans#21]
* [x] Update Version Number
* [x] Update News.md
* [x] Update cran-comments.md
* [x] Check Dependencies
* [x] Run `devtools::release_checks`
